baseURL: https://www.sharestats.nl
title: ShareStats
theme: meghna-hugo
publishDir: "docs"
paginate: '6'
summaryLength: '15'
disqusShortname: ''
disableLanguages: []
params:
  author: Themefisher
  cookies:
    enable: no
    expire_days: 2
  description: Project site for ShareStats
  google_analytics_id: ''
  logo: images/InfShareStatsColor.png
  map:
    enable: no
    gmap_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ
    map_latitude: '51.5223477'
    map_longitude: '-0.1622023'
    map_marker: images/marker.png
  plugins:
    css:
      - link: plugins/bootstrap/bootstrap.min.css
      - link: plugins/themify-icons/themify-icons.css
      - link: plugins/magnific-popup/magnific-popup.css
      - link: plugins/slick/slick.css
      - link: https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap
    js:
      - link: plugins/jquery/jquery.min.js
      - link: plugins/bootstrap/bootstrap.min.js
      - link: plugins/slick/slick.min.js
      - link: plugins/shuffle/shuffle.min.js
      - link: plugins/magnific-popup/jquery.magnific-popup.min.js
      - link: plugins/lazy-load/lozad.min.js
      - link: plugins/google-map/map.js
  post_share: yes
  preloader:
    enable: no
    preloader: images/logo.png
  social:
    # - icon: ti-facebook
    #   link: '#'
    # - icon: ti-twitter-alt
    #   link: '#'
    - icon: ti-github
      link: 'https://github.com/ShareStats'
    - icon: ti-linkedin
      link: 'https://www.linkedin.com/groups/12464778/'
Languages:
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2021 - powered by Hugo
    home: Home
    languageCode: en-us
    languageName: EN
    menu:
      main:
        - name: about
          pre: '#'
          url: feature
          weight: 1
        - name: team
          pre: '#'
          url: team
          weight: 4
        - name: blog
          pre: '#'
          url: blog
          weight: 6
        - name: contact
          pre: '#'
          url: contact
          weight: 7
    weight: 1
  nl:
    contentDir: content/dutch
    copyright: Copyright &copy; 2021 - powered by Hugo
    home: Home
    languageCode: nl-nl
    languageName: NL
    menu:
      main:
        - name: over
          pre: 'nl/#'
          url: feature
          weight: 1
        - name: team
          pre: 'nl/#'
          url: team
          weight: 4
        - name: blog
          pre: 'nl/#'
          url: blog
          weight: 6
        - name: contact
          pre: 'nl/#'
          url: contact
          weight: 7
    weight: 2