---
format: 
  html:
    page-layout: custom
---

```{js, echo=FALSE}
var search = new URLSearchParams(window.location.search);

document.addEventListener('DOMContentLoaded', function() {
    var inputElement = document.querySelector("#DataTables_Table_0_filter input[type='search']");
    
    if(inputElement) {
        inputElement.value = search.get('query');
        inputElement.focus();
        inputElement.click();
        
        // Emulate mouse release (mouseup event)
            var mouseUpEvent = new MouseEvent('mouseup', {
                bubbles: true,
                cancelable: true,
                view: window
            });
            inputElement.dispatchEvent(mouseUpEvent);
    }
});

// Function to force download XML files from github
// Does not work with raw github urls. It needs a Content delivery network (CDN)
function forceDownload(url, filename) {
  fetch(url)
    .then(resp => resp.blob())
    .then(blob => {
      const link = document.createElement('a');
      link.href = window.URL.createObjectURL(blob);
      link.download = filename;
      link.click();
    })
    .catch(console.error);
}
```

::: itembank
# Itembank Search

```{r, include=FALSE}
## Short functions for creating links per item that are used below in the table.
get_link <- function(what, folder, name){
  packages_link <- 'https://github.com/ShareStats/itembank/raw/packages/packages/'
  repo_link <- 'https://sharestats.github.io/itembank/'
  cdn_link <- 'https://cdn.jsdelivr.net/gh/ShareStats/itembank@packages/packages/' # for XML
  link <- switch(what,
                 zip = paste0(packages_link, 'zip/', folder, '.zip'),
                 tv = paste0(packages_link, 'tv/', folder,'-tv.zip'),
                 qti =  paste0(packages_link,'qti/', folder,'-qti.zip'),
                 canvas = paste0(packages_link, 'canvas/', folder,'-canvas.zip'),
                 ans = paste0(packages_link, 'ans/', folder,'-ans.zip'),
                 wooclap = paste0(cdn_link, 'wooclap/', folder, '-wooclap.xml'),
                 html = paste0(repo_link, folder, '/', name, '1.html'), 
                 NULL
                 )
}
```

```{r, include = FALSE}
# Install and load necessary R packages
library(DT)
library(tidyverse)
```

```{r read-file-from-url, include = FALSE}
# Create the columns containing the 'View' and 'Download' buttons
data.path <- "https://sharestats.github.io/itembank/sharestats_website.csv"
dat <- read_csv(data.path) 
```

```{r, include = FALSE}
dat <- dat %>% 
  dplyr::select(-1) %>% 

# New offcanvas view button:
mutate(View = paste0(
    '<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample',id+1,'" role="button" aria-controls="offcanvasExample',id+1,'">
  <i class="bi bi-eye fs-4"></i>
</a>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample',id+1,'" aria-labelledby="offcanvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasLabel">',name,'</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
<embed src="',get_link("html", folder, name),'" width="100%" height="90%">
  </div>
</div>'
    )) %>% 
  # Dropdown Files button
  mutate(Files = paste0(
    '<div class="dropdown mt-3">
      <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-bs-toggle="dropdown" aria-expanded="false">
        <i class="bi bi-cloud-download fs-4"></i>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="">
        <li><a class="dropdown-item" href="',get_link("zip", folder, name),'">ZIP Folder</a></li>
        <li><a class="dropdown-item" href="',get_link("qti", folder, name),'">QTI 2.1</a></li>
        <li><a class="dropdown-item" href="',get_link("tv", folder, name),'">TestVision</a></li>
        <li><a class="dropdown-item" href="',get_link("canvas", folder, name),'">Canvas</a></li>
        <li><a class="dropdown-item" href="',get_link("ans", folder, name),'">Ans</a></li>
        <li><a class="dropdown-item" href="#" onclick="forceDownload(\'', get_link("wooclap", folder, name), '\', \'', name, '-wooclap.xml\'); return false;">Wooclap</a></li>
      </ul>
    </div>'
  )) %>% 
  
  mutate(`Item Name` = name, .before = 1)

```

```{r, echo = FALSE, warning=FALSE, eval=TRUE}

# Create an interactive table using the DT package
dat %>% dplyr::select(-name, -question, -folder, -id) %>% 
datatable(., filter = "top", 
          options = list(pageLength = 10
                         # ,
                         # dom = 'Pfrtip', 
                         # columnDefs = list(list(searchPanes = list(show = FALSE), 
                         #                        targets     = 1:3 ))
                         ),
          # extensions = c('Select', 'SearchPanes'),
          style = 'bootstrap', selection = 'multiple', 
          escape = FALSE
          )
```

<br>

## Read search table into R {#RreadCSV}

You can also load the search table into R as a dataframe. Just copy the code below and you will have access to all the meta information of the items and the github folder location.

```{r, eval=FALSE}
# Read csv
all.items <- read.csv("https://sharestats.github.io/itembank/sharestats_website.csv")

# Add github url
all.items$Path <- paste0("https://github.com/ShareStats/itembank/tree/main/", all.items$folder)

# Show names
names(all.items)
```

:::
